# 101 Pandas Exercises for Data Analysis

[Reference](https://www.machinelearningplus.com/python/101-pandas-exercises-python/)

## 1. Import pandas and check pandas version

In [1]:
import pandas as pd
print(pd.__version__)
print(pd.show_versions(as_json=True))

import numpy as np

0.25.1
{'system': {'commit': None, 'python': '3.7.4.final.0', 'python-bits': 64, 'OS': 'Darwin', 'OS-release': '19.3.0', 'machine': 'x86_64', 'processor': 'i386', 'byteorder': 'little', 'LC_ALL': 'None', 'LANG': 'en_US.UTF-8', 'LOCALE': 'en_US.UTF-8'}, 'dependencies': {'pandas': '0.25.1', 'numpy': '1.17.2', 'pytz': '2019.3', 'dateutil': '2.8.0', 'pip': '19.2.3', 'setuptools': '41.4.0', 'Cython': '0.29.13', 'pytest': '5.2.1', 'hypothesis': None, 'sphinx': '2.2.0', 'blosc': None, 'feather': None, 'xlsxwriter': '1.2.1', 'lxml.etree': '4.4.1', 'html5lib': '1.0.1', 'pymysql': None, 'psycopg2': None, 'jinja2': '2.10.3', 'IPython': '7.8.0', 'pandas_datareader': None, 'bs4': '4.8.0', 'bottleneck': '1.2.1', 'fastparquet': None, 'gcsfs': None, 'matplotlib': '3.1.1', 'numexpr': '2.7.0', 'odfpy': None, 'openpyxl': '3.0.0', 'pandas_gbq': None, 'pyarrow': None, 'pytables': None, 's3fs': None, 'scipy': '1.3.1', 'sqlalchemy': '1.3.9', 'tables': '3.5.2', 'xarray': None, 'xlrd': '1.2.0', 'xlwt': '1.3.0'

## 2. How to create a series from a list, numpy array or dict

Create a pandas series from each of the items below: a list, numpy and a dictionary.

Input:

```
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
```

In [6]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

list_series = pd.Series(mylist)
arr_series = pd.Series(myarr)
dict_series = pd.Series(mydict)

print(list_series.head())
print(arr_series.head())
print(dict_series.head())

0    a
1    b
2    c
3    e
4    d
dtype: object
0    0
1    1
2    2
3    3
4    4
dtype: int64
a    0
b    1
c    2
e    3
d    4
dtype: int64


## 3. How to convert the index of a series into a column of a dataframe?

Convert the series `ser` into a dataframe with its index as another column on the dataframe.

Input:

```
mylist = list('abcedfghijklmnopqrstuvwxyz')
mydict = dict(zip(mylist, myarr))
mydict = pd.Series(mydict)
```

In [11]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

mydf = ser.to_frame().reset_index()
print(mydf.head())

  index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4


## 4. How to combine many series to form a dataframe?

Combine ser1 and ser2 to form a dataframe.

Input:

```
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
```

In [16]:
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

mydf = pd.DataFrame({
    'col1': ser1,
    'col2': ser2
})
mydf.head()

col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4

## 5. How to assign name to the series' index?

Give a name to the series `ser1` calling it `alphabets`.

Input:

```
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
```

In [20]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

ser.name = 'alphabets'
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: alphabets, dtype: object

## 6. How to get the items of series A not present in series B?

From `ser1` remove items present in `ser2`.

```
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
```

In [25]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

## 7. How to get the items not common to both series A and series B?

Get all items of `ser1` and `ser2` not common to both.

```
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
```

In [29]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

ser_u = pd.Series(np.union1d(ser1, ser2)) # union
ser_i = pd.Series(np.intersect1d(ser1, ser2)) # intersection

ser_u[~ser_u.isin(ser_i)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

## 8. How to get the minimum, 25th percentile, median, 75th percentile, and max of a numeric series?

```
ser = pd.Series(np.random.normal(10, 5, 25))
```

In [43]:
state = np.random.RandomState(100)
ser = pd.Series(state.normal(10, 5, 25))

np.percentile(ser, q = [0, 25, 50, 75, 100])

array([ 1.25117263,  7.70986507, 10.92259345, 13.36360403, 18.0949083 ])

## 9. How to get frequency counts of unique items of a series?

Calculate the frequency counts of each unique value `ser`.

```
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
```

In [47]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

ser.value_counts()

a    7
f    6
g    5
e    4
b    3
c    2
d    2
h    1
dtype: int64

## 10. How to keep only the top 2 most frequent values as it is and replace everything else as 'Other'?

From `ser`, keep the top 2 most frequent items as it is and replace everything else as 'Other'.

```
state = np.random.RandomState(100)
ser = pd.Series(state.randint(1, 5, [12]))
```

In [52]:
state = np.random.RandomState(100)
ser = pd.Series(state.randint(1, 5, [12]))

print(ser.value_counts())
ser[~ser.isin(ser.value_counts().index[:2])] = 'Other'
ser

4    4
1    4
3    3
2    1
dtype: int64


0         1
1         1
2         4
3         4
4         4
5         4
6         1
7     Other
8     Other
9         1
10    Other
11    Other
dtype: object

## 11. How to bin a numeric series to 10 groups of equal size?

Bin the series `ser` into 10 equal deciles and replace the values with the bin name.

Input:

```
ser = pd.Series(np.random.random(20))
```

Desired Output:

```
# First 5 items
0    7th
1    9th
2    7th
3    3rd
4    8th
dtype: category
Categories (10, object): [1st < 2nd < 3rd < 4th ... 7th < 8th < 9th < 10th]
```

In [62]:
state = np.random.RandomState(100)

ser = pd.Series(state.random(20))
print(ser.head())

pd.qcut(ser, q = [0, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 1.00],
       labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']) \
    .head()

0    0.543405
1    0.278369
2    0.424518
3    0.844776
4    0.004719
dtype: float64


0    6th
1    5th
2    6th
3    9th
4    1st
dtype: category
Categories (10, object): [1st < 2nd < 3rd < 4th ... 7th < 8th < 9th < 10th]

## 12. How to convert a numpy array to a dataframe of given shape?

Reshape the series `ser` into a dataframe with 7 rows and 5 columns.

```
ser = pd.Series(np.random.randint(1, 10, 35))
```

In [70]:
ser = pd.Series(np.random.randint(1, 10, 35))
df = pd.DataFrame(ser.values.reshape(7, 5))
print(df)

   0  1  2  3  4
0  8  9  6  2  7
1  1  3  6  3  8
2  2  2  8  9  2
3  9  3  3  1  4
4  8  5  8  3  1
5  2  4  5  7  6
6  5  1  6  6  4


## 13. How to find the positions of numbers that are multiples of 3 from a Series?

Find the positions of numbers that are multiples of 3 from `ser`.

```
ser = pd.Series(np.random.randint(1, 10, 7))
```

In [79]:
state = np.random.RandomState(100)
ser = pd.Series(state.randint(1, 10, 7))
print(ser)

np.argwhere(ser.values % 3==0)

0    9
1    9
2    4
3    8
4    8
5    1
6    5
dtype: int64


array([[0],
       [1]])

## 14. How to extract items at given positions from a series?

From `ser`, extract the items at positions in list `pos`.

Input: 

```
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
```

In [81]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

print(ser[ser.index.isin(pos)])

# Solution from reference
ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object


0     a
4     e
8     i
14    o
20    u
dtype: object

## 15. How to stack two series vertically and horizontally?

Stack `ser1` and `ser2` vertically and horizontally (to form a dataframe).

Input:

```
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
```

In [87]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

# Vertical
print(pd.concat([ser1, ser2], axis=0))
# Alternate vertical
print(ser1.append(ser2))

# Horizontal
print(pd.concat([ser1, ser2], axis=1))

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object
0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object
   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


## 16. How to get the positions of items of series A in another series B?

Get the positions of items of `ser2` in `ser` as a list.

Input:

```
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])
```

In [95]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

# Solution 1
[np.where(i == ser1)[0].tolist()[0] for i in ser2]

# Solution 2
[pd.Index(ser1).get_loc(i) for i in ser2]

[5, 4, 0, 8]

## 17. How to compute the mean squared error on a truth and predicted series?

Compute the mean squared error of `truth` and `pred` series.

Input:

```
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)
```

In [96]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

np.mean((truth - pred)**2)

0.435503213830999

## 18. How to convert the first character of each element in a series to uppercase?

Change the first character of each word to upper case in each word of `ser`.

Input:

```
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
```

In [102]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

# Solution 1
ser.map(lambda x: x.title())

# Solution 2
ser.map(lambda x: x[0].upper() + x[1:])

# Solution 3
pd.Series([i.title() for i in ser])

0     How
1      To
2    Kick
3    Ass?
dtype: object

## 19. How to calculate the number of characters in each word in a series?

Input:

```
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
```

In [107]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

# Solution 1
print(pd.Series([len(i) for i in ser]))

# Solution 2
print(ser.map(lambda x: len(x)))

0    3
1    2
2    4
3    4
dtype: int64
0    3
1    2
2    4
3    4
dtype: int64


## 20. How to compute difference of differences between consequtive numbers of a series?

Difference of differences between consequtive numbers of `ser`.

Input:

```
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
```

Desired Output:

```
[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]
```

In [112]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

print(ser.diff().tolist())
print(ser.diff().diff().tolist())

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


## 21. How to convert a series of date-strings to a timeseries?

Input:

```
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
```

Desired Output:

```
0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]
```

In [115]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Solution 1
from dateutil.parser import parse
ser.map(lambda x: parse(x))

# Solution 2
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

## 22. How to get the day of month, week number, day of year and day of week from a series of date strings?

Input:

```
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
```

Desired Output:

```
Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day num of year:  [1, 33, 63, 94, 125, 157]
Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']
````

In [148]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
ser_ts = pd.to_datetime(ser)

print(f'Date: {ser_ts.dt.day.tolist()}')
print(f'Week number: {ser_ts.dt.weekofyear.tolist()}')
print(f'Day num of year: {ser_ts.dt.dayofyear.tolist()}')
day_of_week={0:'Monday', 1:'Tuesday', 2:'Wednesday', 3:'Thursday', 4:'Friday', 5:'Saturday', 6:'Sunday'}
print(f'Day of week: {ser_ts.dt.weekday.map(lambda x: day_of_week[x]).tolist()}')



Date: [1, 2, 3, 4, 5, 6]
Week number: [53, 5, 9, 14, 19, 23]
Day num of year: [1, 33, 63, 94, 125, 157]
Day of week: ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


## 23. How to convert year-month string to dates corresponding to the 4th day of the month?

Change `ser` to dates that start with 4th of the respective months.

Input:

```
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
```

Desired Output:

```
0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]
```

In [154]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
ser_ts = [i + pd.DateOffset(days=3) for i in pd.to_datetime(ser)]

# format the string
pd.Series([i.strftime('%Y-%m-%d') for i in ser_ts])

0    2010-01-04
1    2011-02-04
2    2012-03-04
dtype: object

## 24. How to filter words that contain at least 2 vowels from a series?

**Level 3**

From `ser`, extract words that contain at least 2 vowels.

Input:

```
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
```

Desired Output:

```
0     Apple
1    Orange
4     Money
dtype: object
```

In [186]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

from collections import Counter
mask = ser.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiou')]) >= 2)

ser[mask]

0     Apple
1    Orange
4     Money
dtype: object

## 25. How to filter valid emails from a series?

**Level 3**

Extract the valid emails from the series `emails`. The regex pattern for valid emails is provided as reference.

Input:

```
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
```

Desired Output:

```
1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object
```

In [192]:
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

# Solution 1 (as a series of strings)
import re
mask = emails.map(lambda x: bool(re.match(pattern, x)))
print(emails[mask])

# Solution 2 (as a series of lists)
print(emails.str.findall(pattern, flags=re.IGNORECASE))

# Solution 3 (as list)
print(pd.Series([x[0] for x in [re.findall(pattern, email) for email in emails] if len(x) > 0]))

1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object
0                     []
1    [rameses@egypt.com]
2            [matt@t.co]
3    [narendra@modi.com]
dtype: object
0    rameses@egypt.com
1            matt@t.co
2    narendra@modi.com
dtype: object


## 26. How to get the mean of a series grouped by another series?

Compute the mean of `weights` of each `fruit`.

Input:

```
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weight.tolist())
print(fruit.tolist())
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']
```

Desired Output:

```
# values can change due to randomness
apple     6.0
banana    4.0
carrot    5.8
dtype: float64
```

In [202]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
# print(weights.tolist())
# print(fruit.tolist())

df = pd.DataFrame({
    'fruit': fruit,
    'weight': weights
}).groupby(fruit).mean()
df

weight
apple     10.0
banana     3.0
carrot     6.6

## 27. How to compute the Euclidean distance bewteen two series?

Compute the **Euclidean distance** between series (points) p and q, without using a packaged formula.

Input:

```
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
```

Desired Output:

```
18.165
```

In [215]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

print(np.sqrt(np.sum((p - q)**2)))

print(np.linalg.norm(p - q))

18.16590212458495
18.16590212458495


## 28. How to find all the local maxima (or peaks) in a numeric series?

Get the positions of peaks (values surrounded by smaller values on both sides) in `ser`.

Input:

```
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
```

Desired Output:

```
array([1, 5, 7])
```

In [228]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

dd = np.diff(np.sign(np.diff(ser)))
dd

print(np.diff(ser))
print(np.sign(np.diff(ser)))
print(dd)

peak_locs = np.where(dd == -2)[0] + 1
peak_locs

[ 8 -7  1  5  1 -8  5 -4]
[ 1 -1  1  1  1 -1  1 -1]
[-2  2  0  0 -2  2 -2]


array([1, 5, 7])

## 29. How to replace missing spaces in a string with the least frequent character?

Replace the spaces in `my_str` with the least frequent character.

Input:

```
my_str = 'dbc deb abed gade'
```

Desired Output:

```
'dbccdebcabedcgade'  # least frequent is 'c'
```

In [246]:
my_str = 'dbc deb abed gade'

freq = pd.Series(list(my_str)).value_counts()
print(freq)
least_freq = freq.dropna().index[-1]

my_str.replace(' ', least_freq)

d    4
e    3
     3
b    3
a    2
c    1
g    1
dtype: int64


'dbcgdebgabedggade'

## 30. How to create a TimeSeries starting '2000-01-01' and 10 weekends (Saturdays) after that having random numbers as values?

Desired Output:

```
# values can be random
2000-01-01    4
2000-01-08    1
2000-01-15    8
2000-01-22    4
2000-01-29    4
2000-02-05    2
2000-02-12    4
2000-02-19    9
2000-02-26    6
2000-03-04    6
```

In [257]:
pd.DataFrame({
    'date': pd.date_range('2000-01-01', periods=10, freq='W-SAT'),
    'value': np.random.randint(0, 10, size=10)
})

date  value
0 2000-01-01      1
1 2000-01-08      2
2 2000-01-15      4
3 2000-01-22      0
4 2000-01-29      3
5 2000-02-05      8
6 2000-02-12      3
7 2000-02-19      4
8 2000-02-26      5
9 2000-03-04      8

## 31. How to fill an intermittent time series so all missing dates show up with values of previous non-missing date?

`ser` has missing dates and values. Make all missing dates appear and fill up with value from previous date.

Input:

```
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
```

Desired Output:

```
2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
```

In [262]:
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)

# Solution
res1 = ser.resample('D').ffill()
print('Solution 1')
print(res1)

# Alternative solutions
res2 = ser.resample('D').bfill() # Fill with next value
print('Solution 2')
print(res2)

res3 = ser.resample('D').bfill().ffill()
print('Solution 3')
print(res3)

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64
Solution 1
2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64
Solution 2
2000-01-01     1.0
2000-01-02    10.0
2000-01-03    10.0
2000-01-04     3.0
2000-01-05     3.0
2000-01-06     3.0
2000-01-07     NaN
2000-01-08     NaN
Freq: D, dtype: float64
Solution 3
2000-01-01     1.0
2000-01-02    10.0
2000-01-03    10.0
2000-01-04     3.0
2000-01-05     3.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     3.0
Freq: D, dtype: float64


## 32. How to compute the autocorrelations of a numeric series?

Compute autocorrelations for the first 10 lags of `ser`. Find out which lag has the largest correlation.

Input:

```
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))
```

Desired Output:

```
# values will change due to randomness
[0.29999999999999999, -0.11, -0.17000000000000001, 0.46000000000000002, 0.28000000000000003, -0.040000000000000001, -0.37, 0.41999999999999998, 0.47999999999999998, 0.17999999999999999]
Lag having highest correlation:  9
```

In [18]:
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))
window_size = 10
print(len(ser))
autocorrelations = [ser.autocorr(i).round(2) for i in range(window_size)]
print(autocorrelations[1:])
print(f'{np.argmax(autocorrelations[1:])}')

20
[-0.35, -0.01, -0.04, 0.12, 0.15, 0.01, 0.07, -0.41, 0.68]
8


## 33. How to import only every nth row from a csv file to create a dataframe?

Import every 50th row of [boston housing dataset](https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv) as a dataframe.

In [37]:
# df_boston = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv')

# Solution 1: Use chunks and for-loop
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv',
                 chunksize=50)
df2 = pd.DataFrame()
for chunk in df:
    df2 = df2.append(chunk.iloc[0,:])
print('Solution 1')
print(df2.head())

# Solution 2: Use chunks and list comprehension
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv',
                 chunksize=50)
df2 = pd.concat([chunk.iloc[0] for chunk in df], axis = 1)
df2 = df2.transpose()
print('Solution 2')
print(df2.head())

Solution 1
      age       b  chas     crim     dis  indus  lstat  medv    nox  ptratio  \
0    65.2  396.90   0.0  0.00632  4.0900   2.31   4.98  24.0  0.538     15.3   
50   45.7  395.56   0.0  0.08873  6.8147   5.64  13.45  19.7  0.439     16.8   
100  79.9  394.76   0.0  0.14866  2.7778   8.56   9.42  27.5  0.520     20.9   
150  97.3  372.80   0.0  1.65660  1.6180  19.58  14.10  21.5  0.871     14.7   
200  13.9  384.30   0.0  0.01778  7.6534   1.47   4.45  32.9  0.403     17.0   

     rad     rm    tax    zn  
0    1.0  6.575  296.0  18.0  
50   4.0  5.963  243.0  21.0  
100  5.0  6.727  384.0   0.0  
150  5.0  6.122  403.0   0.0  
200  3.0  7.135  402.0  95.0  
Solution 2
        crim    zn  indus  chas    nox     rm   age     dis  rad    tax  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
50   0.08873  21.0   5.64   0.0  0.439  5.963  45.7  6.8147  4.0  243.0   
100  0.14866   0.0   8.56   0.0  0.520  6.727  79.9  2.7778  5.0  384.0   
150  1.6566

## 34. How to change column values when importing csv to dataframe?

Import the [boston housing dataset](https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv), but while importing change the `medv` [median house value] column so that the values <25 become `Low` and > 25 becomes `High`.

In [40]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv',
                converters={'medv': lambda x: 'High' if float(x) > 25 else 'Low'})
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98   Low  
1  396.90   9.14   Low  
2  392.83   4.03  High  
3  394.63   2.94  High  
4  396.90   5.33  High

## 35. How to create a dataframe with rows as strides from a given series?

Input:

```
L = pd.Series(range(15))
```

Desired Output:


```
array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])
```

In [49]:
L = pd.Series(range(15))

def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

gen_strides(L, stride_len=2, window_len=4)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])

## 36. How to import only specified columns from a csv file?

Import `crim` and `medv` columns of the Boston Housing dataframe.

In [52]:
columns_to_import = ['crim', 'medv']
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv',
                usecols=columns_to_import)
df.head()

crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2

## 37. How to get the nrows, ncolumns, datatype, summary stats of each column of a dataframe? Also, get the array and list equivalent.

Get the number of rows, columns, datatype, and summary statistics of each column of the Cars93 dataset. Also get the numpy array and list equivalent of the dataframe.

In [62]:
cars_url = 'https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'

df = pd.read_csv(cars_url)

# Number of rows and columns
print(df.shape)

# datatypes
print('\n DataTypes:')
print(df.dtypes)

# how many columns under each dtype
print('\n DType value counts')
print(df.dtypes.value_counts())

# Summary Statistics
print('\n Summary Statistics')
print(df.describe())

# numpy array
df_arr = df.values

# list
df_list = df.values.tolist()

(93, 27)

 DataTypes:
Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city              float64
MPG.highway           float64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower            float64
RPM                   float64
Rev.per.mile          float64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers            float64
Length                float64
Wheelbase             float64
Width                 float64
Turn.circle           float64
Rear.seat.room        float64
Luggage.room          float64
Weight                float64
Origin                 object
Make                   object
dtype: object

 DType value counts
float64    18
object      9
dtype: int64

 Summary Statistics
       Min.Price      Price  Max.Price   MPG.city  MPG.highway  EngineS

## 38. How to extract the row and column number of a particular cell with given criterion?

Input:

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

Which manufacturer, model and type has the highest `Price`? What is the row and column number of the cell with the highest `Price` value?

In [113]:
df = pd.read_csv(cars_url)
# print(df.head())

df.loc[df.Price == np.max(df['Price']), ['Manufacturer', 'Price', 'Type']]

# Get Row and Column number
row, col = np.where(df.values == np.max(df.Price))

print(row)
print(col)

# Get the value
df.iat[row[0], col[0]]
df.iloc[row[0], col[0]]

[58]
[4]


61.9

In [98]:
print(df.groupby('Type').agg({'Price': ['mean', 'sum'], 'MPG.city': ['min', 'max']}))
# print(df.head())

             Price        MPG.city      
              mean    sum      min   max
Type                                    
Compact  18.212500  291.4     20.0  26.0
Large    24.300000  267.3     16.0  20.0
Midsize  27.647619  580.6     16.0  23.0
Small    10.200000  193.8     23.0  46.0
Sporty   20.316667  243.8     17.0  30.0
Van      19.100000  171.9     15.0  18.0


## 39. How to rename specific columns in a dataframe?

Rename the column `Type` as `CarType` in `df` and replace the `.` in column names with `_`.

Input:

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.columns)
#> Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
#>        'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
#>        'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
#>        'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
#>        'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
#>        'Make'],
#>       dtype='object')
```

Desired Output:

```
print(df.columns)
#> Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
#>        'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
#>        'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
#>        'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
#>        'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
#>        'Make'],
#>       dtype='object')

```

In [120]:
df = pd.read_csv(cars_url)
print(' Original Columns:')
print(df.columns)

df.rename(columns = {
    'Type': 'CarType'
}, inplace = True)

columns_df = df.columns.map(lambda x: x.replace('.', '_'))
df.columns = columns_df

print('\n Updated Columns:')
print(df.columns)

 Original Columns:
Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')

 Updated Columns:
Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


## 40. How to check if a dataframe has any missing values?

Check if `df` has any missing values.

Input:

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [138]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Are there any missing values in df?
df.isnull().values.any()

True

In [141]:
# Get the percentage of missing values
print(f'Total number of values in df: {np.product(df.shape)}')
print(f'Number of missing values in df: {df.isnull().values.sum()}')
print(f'Percentage of missing values in df: {df.isnull().values.sum() / np.product(df.shape) * 100}%')

Total number of values in df: 2511
Number of missing values in df: 138
Percentage of missing values in df: 5.4958183990442055%


## 41. How to count the number of missing values in each column?

Count the number of missing values in each column of `df`. Which column has the maximum number of missing values?

Input:

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [147]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df.apply(lambda x: x.isnull().sum())

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

## 42. How to replace missing values of multiple numeric columns with the mean?

Replace missing values in `Min.Price` and `Max.Price` columns with their respective mean.

Input:

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [181]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Alternate solution
df_out = df[['Min.Price', 'Max.Price']].apply(lambda x: x.fillna(x.mean()))
print(df_out.head())


   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


## 43. How to use apply function on existing columns with global variables as additional arguments?

In `df`, use `apply` method to replace the missing values in `Min.Price` with the column's mean and those in `Max.Price` with the column's median.

Input:

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [190]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
dmap = {'Min.Price': np.nanmean, 'Max.Price': np.nanmedian}
df[['Min.Price', 'Max.Price']].apply(lambda x, d: x.fillna(d[x.name](x)), args=(dmap, ))

Min.Price  Max.Price
0   12.900000      18.80
1   29.200000      38.70
2   25.900000      32.30
3   17.118605      44.60
4   17.118605      19.15
..        ...        ...
88  16.600000      22.70
89  17.600000      22.40
90  22.900000      23.70
91  21.800000      23.50
92  24.800000      28.50

[93 rows x 2 columns]

## 44. How to select a specific column from a dataframe as a dataframe instead of a series?

Get the first column[`a`] in `df` as a dataframe [rather than as a Series].

Input:

```
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
```

In [198]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
type(df[['a']])

pandas.core.frame.DataFrame

## 45. How to change the order of columns of a dataframe?

Actually 3 questions:

1. In `df`, interchange columns `a` and `c`.
2. Create a generic function to interchange two columns, without hardcoding column names.
3. Sort the columns in reverse alphabetical order, that is column `e` first through column `a` last.

Input:

```
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
```

In [205]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

print(df[list('cbade')])


def interchange_cols(df, first, second):
    colnames = df.columns.tolist()
    i1, i2 = colnames.index(first), colnames.index(second)
    colnames[i1], colnames[i2] = colnames[i2], colnames[i1]
    return df[colnames]
    
df1 = interchange_cols(df, 'a', 'c')
print(df1)

    c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19
    c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19


## 46. How to set the number of rows and columns displayed in the output?

Change the pandas display settings on printing the dataframe `df` it shows a maximum of 6 rows and 6 columns.

Input:

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [222]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

pd.set_option('display.max_rows', 6)
pd.set_option('display.max_columns', 6)
df

Manufacturer    Model     Type  ...  Weight   Origin                Make
0         Acura  Integra    Small  ...  2705.0  non-USA       Acura Integra
1           NaN   Legend  Midsize  ...  3560.0  non-USA        Acura Legend
2          Audi       90  Compact  ...  3375.0  non-USA             Audi 90
..          ...      ...      ...  ...     ...      ...                 ...
90   Volkswagen  Corrado   Sporty  ...  2810.0  non-USA  Volkswagen Corrado
91        Volvo      240  Compact  ...  2985.0  non-USA           Volvo 240
92          NaN      850  Midsize  ...  3245.0  non-USA           Volvo 850

[93 rows x 27 columns]

## 47. How to format or suppress scientific notations in a pandas dataframe?

Suppress scientific notations like `e-03` in `df` and print up to 4 numbers after decimal.

Input:

```
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])
df
#>          random
#> 0  3.474280e-03
#> 1  3.951517e-05
#> 2  7.469702e-02
#> 3  5.541282e-28
```

In [234]:
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])
df

random
0  3.449683e-02
1  4.762403e-03
2  4.541508e-09
3  3.043601e-01

In [235]:
# Solution 1: Rounding
df.round(4)

random
0  0.0345
1  0.0048
2  0.0000
3  0.3044

In [225]:
# Solution 2: Use apply to change format
df.apply(lambda x: '%.4f' % x, axis = 1)

0    0.0266
1    0.0000
2    0.3971
3    0.0106
dtype: object

In [227]:
df.applymap(lambda x: '%.4f' % x)

random
0  0.0266
1  0.0000
2  0.3971
3  0.0106

In [229]:
# Solution 3: Use set_option
pd.set_option('display.float_format', lambda x: '%.4f' % x)
df

random
0  0.0266
1  0.0000
2  0.3971
3  0.0106

In [237]:
# Reset/undo float formatting
pd.options.display.float_format = None
df

random
0  3.449683e-02
1  4.762403e-03
2  4.541508e-09
3  3.043601e-01

## 48. How to format all the values in a dataframe as percentages?

Format the values in column `random` of `df` as percentages.

Input:

```
df = pd.DataFrame(np.random.random(4), columns=['random'])
df
```

In [239]:
df = pd.DataFrame(np.random.random(4), columns=['random'])

out = df.style.format({
    'random': '{0:.2%}'.format
})
out

## 49. How to filter every nth row in a dataframe?

From `df`, filter the `Manufacturer`, `Model`, and `Type` for every 20th row starting from the 1st [row 0].

Input:

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')


print(df.iloc[::20, :][['Manufacturer', 'Model', 'Type']])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


## 50. How to create a primary key index by combining relevant columns?

In `df`, replace `NaN`s with `missing` in columns `Manufacturer`, `Model`, and `Type` and create an index as a combination of these three columns and check if the index is a primary key.

Input:

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])
```

Desired Output:

```
                       Manufacturer    Model     Type  Min.Price  Max.Price
Acura_Integra_Small           Acura  Integra    Small       12.9       18.8
missing_Legend_Midsize      missing   Legend  Midsize       29.2       38.7
Audi_90_Compact                Audi       90  Compact       25.9       32.3
Audi_100_Midsize               Audi      100  Midsize        NaN       44.6
BMW_535i_Midsize                BMW     535i  Midsize        NaN        NaN
```

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])
df

Manufacturer    Model     Type  Min.Price  Max.Price
0         Acura  Integra    Small       12.9       18.8
1           NaN   Legend  Midsize       29.2       38.7
2          Audi       90  Compact       25.9       32.3
3          Audi      100  Midsize        NaN       44.6
4           BMW     535i  Midsize        NaN        NaN
..          ...      ...      ...        ...        ...
88   Volkswagen  Eurovan      Van       16.6       22.7
89   Volkswagen   Passat  Compact       17.6       22.4
90   Volkswagen  Corrado   Sporty       22.9       23.7
91        Volvo      240  Compact       21.8       23.5
92          NaN      850  Midsize       24.8       28.5

[93 rows x 5 columns]

In [14]:
df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')
df.index = df.Manufacturer + '_' + df.Model + '_' + df.Type
print(df)
print(df.index.is_unique)

                          Manufacturer    Model     Type  Min.Price  Max.Price
Acura_Integra_Small              Acura  Integra    Small       12.9       18.8
missing_Legend_Midsize         missing   Legend  Midsize       29.2       38.7
Audi_90_Compact                   Audi       90  Compact       25.9       32.3
Audi_100_Midsize                  Audi      100  Midsize        NaN       44.6
BMW_535i_Midsize                   BMW     535i  Midsize        NaN        NaN
...                                ...      ...      ...        ...        ...
Volkswagen_Eurovan_Van      Volkswagen  Eurovan      Van       16.6       22.7
Volkswagen_Passat_Compact   Volkswagen   Passat  Compact       17.6       22.4
Volkswagen_Corrado_Sporty   Volkswagen  Corrado   Sporty       22.9       23.7
Volvo_240_Compact                Volvo      240  Compact       21.8       23.5
missing_850_Midsize            missing      850  Midsize       24.8       28.5

[93 rows x 5 columns]
True


## 51. How to get the row number of the nth largest value in a column?

Find the row position of the 5th largest value of column `a` in `df`.

Input:

```
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
```

In [15]:
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
df

a   b   c
0  23  20   2
1   7  19   7
2  21  25  22
3  13  19  14
4   4   2  20
5  13  18  20
6  16   6  27
7  22  24   7
8  12   1   7
9  28  15  27

In [22]:
n = 5
df.sort_values('a', ascending=False).index[n-1]

6

In [31]:
# Solution
df['a'].argsort()[::-1][n]

6

## 52. How to find the position of the nth largest value greater than a given value?

In `ser`, find the position of the 2nd largest value greater than the mean.

Input:

```
ser = pd.Series(np.random.randint(1, 100, 15))
```

In [32]:
ser = pd.Series(np.random.randint(1, 100, 15))
ser

0     97
1     59
2     76
3      1
4     51
5     58
6     59
7     36
8     12
9     81
10    26
11    26
12    56
13    57
14    33
dtype: int64

In [44]:
np.argwhere(ser > ser.mean())[1]

array([1])

## 53. 