# 101 Numpy Exercises for Data Science

[Reference](https://www.machinelearningplus.com/python/101-numpy-exercises-python/)

## 1. Import numpy as np and see the version

Q: Import numpy as `np` and print the version number

In [2]:
import numpy as np

print(np.__version__)

1.17.2


## 2. How to create a 1D array?

Q: Create a 1D array of numbers from 0 to 9.

Desired output:

```
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [3]:
np.array([x for x in range(10)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3. How to create a boolean array

Q: Create a 3x3 numpy array of all True's

In [5]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
# alternative method
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## 4. How to extract items that satisfy a given condition from 1D array?

Q: Extract all odd numbers from `arr`

Input:
```
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Desired output:
```
#> array([1, 3, 5, 7, 9])
```

In [9]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0]

array([1, 3, 5, 7, 9])

## 5. How to replace items that satisfy a condition with another value in numpy array?

Q: Replace all odd numbers in `arr` with -1

Input:
```
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Desired output:
```
#> array([0, -1, 2, -1, 4, -1, 6, -1, 8, -1])
```

In [12]:
arr[arr % 2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 6. How to replace items that satisfy a ondition without affecting the original array?

Q: Replace all odd numbers in arr with -1 without changing `arr`

Input:
```
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Desired output:
```
out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [19]:
arr = np.arange(10)
out = np.where(arr % 2 != 0, -1, arr)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [16]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 7. How to reshape an array?

Q: Convert a 1D array to a 2D array with 2 rows

Input:
```
arr = np.arange(10)
arr
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Desired output:
```
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])
```

In [22]:
arr = np.arange(10)
arr.reshape(2, -1) # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 8. How to stack two arrays vertically?

Q: Stack arrays `a` and `b` vertically?

Input:
```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

Desired output:
```
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])
```

In [24]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## 9. How to stack two arrays horizontally?

Q: Stack the arrays `a` and `b` horizontally.

Input:
```
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
```

Desired output:
```
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [27]:
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## 10. How to generate custom sequemces in numpy without hardcoding?

Q: Create the following pattern without hardcoding. Use only numpy functions and the below input array `a`.

Input:
```
a = np.array([1, 2, 3])
```

Desired output:
```
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [52]:
a = np.array([1, 2, 3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [53]:
# Alternative method
np.hstack([a.repeat(3), np.tile(a, 3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## 11. How to get the common items between two python numpy arrays?

Q: Get the common items between `a` and `b`

Input:
```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

Desired output:
```
array([2, 4])
```

In [57]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

## 12. How to remove from one array those items that exist in another?

Q. From array `a` remove all items present in array `b`.

Input:
```
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```

Desired output:
```
#> array([1,2,3,4])
```

In [3]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [5]:
np.setdiff1d(a, b)

array([1, 2, 3, 4])

## 13. How to get the positions where elements of two arrays match?

Q. Get the positions where elements of `a` and `b` match.

Input:
```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

Desired output:
```
#> (array([1, 3, 5, 7]),)
```

In [7]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [8]:
np.where(a == b)

(array([1, 3, 5, 7]),)